blog/apps/blog_auth/urls.py
from django.urls import path
from .views import RegistrarseView, LoguearseView
from django.contrib.auth.views import LogoutView

app_name = 'apps.blog_auth'

urlpatterns = [
    path('registro/', RegistrarseView.as_view(), name = 'registro'),
    path('sesion/', LoguearseView.as_view(), name = 'sesion'),
    path('cerrar_sesion/', LogoutView.as_view(), name = 'cerrar_sesion')
]

blog/apps/post/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import AgregarArticulo, ActualizarArticulo, EliminarArticulo, ListarArticulos

app_name = 'apps.post'

urlpatterns = [
    path('agregar_articulo/', AgregarArticulo.as_view(), name = 'agregar_articulo'),
    path('actualizar_articulo/', ActualizarArticulo.as_view(), name = 'actualizar_articulo'),
    path('eliminar_articulo/', EliminarArticulo.as_view(), name = 'eliminar_articulo'),
    path('listar_articulos/', ListarArticulos.as_view(), name = 'listar_articulos'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import index
from apps.blog_auth.views import RegistrarseView


urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('apps.blog_auth.urls')),
    path('articulos/', include('apps.post.urls')),
]

blog/apps/blog_auth/models.py
from django.db import models

# Create your models here.

blog/apps/post/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=30, null=False)

    def __str__(self) -> str:
        return self.nombre

class Articulo(models.Model):
    titulo = models.CharField(max_length=50, null=False)
    subtitulo = models.CharField(max_length=100, null=False, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    texto = models.TextField(null=False)
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, default='Sin categoria')
    imagen = models.ImageField(null=True, blank=True, upload_to='media', default='static/post_default.png')
    publicado = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publicado',)

    def __str__(self) -> str:
        return self.titulo
    
    def delete(self, using = None, keep_parents = False):
        self.imagen.delete(self.imagen.name)
        super().delete()

blog/apps/blog_auth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrarseForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

blog/apps/blog_auth/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.auth.views import LoginView
from .forms import RegistrarseForm

class RegistrarseView(FormView):
    template_name = 'users/registro.html'
    form_class = RegistrarseForm
    success_url = reverse_lazy('index')

    def form_valid(self, form) -> HttpResponse:
        form.save()
        return super().form_valid(form)
    
class LoguearseView(LoginView):
    template_name = 'users/sesion.html'

# Create your views here.

blog/apps/post/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Articulo

# Create your views here.
class AgregarArticulo(CreateView):
    model = Articulo
    template_name = 'articulos/agregar_articulo.html'
    fields = ['titulo','subtitulo','texto','categoria','imagen']
    success_url = reverse_lazy('index')

class ActualizarArticulo(UpdateView):
    model = Articulo
    template_name = 'articulos/actualizar_articulo.html'
    fields = ['titulo','subtitulo','texto','categoria','imagen']
    success_url = reverse_lazy('index')

class EliminarArticulo(DeleteView):
    model = Articulo
    template_name = 'articulos/Eliminar_articulo.html'
    success_url = reverse_lazy('index')

class ListarArticulos(ListView):
    model = Articulo
    template_name = 'articulos/listar_articulos.html'
    context_object_name = 'articulos'
    paginate_by = 3

    def get_context_data(self):
        context = super().get_context_data()
        articulos = Articulo.objects.all()
        context['articulos'] = articulos
        return context
    

blog/blog/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

blog/templates/articulos/actualizar_articulo.html
{% extends 'base.html' %}
{% load static %}

blog/templates/articulos/agregar_articulo.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
<title>Agregar artículo</title>
{% endblock %}

{% block contenido %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Agregar articulo</h1>
    <p>Ingrese los datos y presione el boton de guardar</p>
    {{ form.as_p }}
   
    <input type="submit" class="btn btn-primary" value="Guardar">
</form>

{% endblock %}

blog/templates/articulos/eliminar_articulo.html
{% extends 'base.html' %}
{% load static %}

blog/templates/articulos/listar_articulo.html
{% extends 'base.html' %}
{% load static %}

blog/templates/articulos/listar_articulos.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<h1>Articulos</h1>
<div class="container-fluid">
    {% for p in articulos %}
    <br>
        <li>{{p.titulo}}</li>
        <li>{{p.subtitulo}}</li>
        <li>{{p.fecha}}</li>
        <li>{{p.categoria}}</li>
    <br>
    {%empty%}
    <h1>No hay registros</h1>
    {% endfor %}

</div>
{% endblock %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/estilos.css'%}">
</head>
<body>
    <div>
        {% block navegacion %}
        {% endblock %}
    </div>
        {% block contenido %}
        {% endblock %}
    <div>

    </div>
</body>
</html>

blog/templates/index.html
{% extends 'base.html'%}
{% load static %}
{% block titulo %}
<title>Inicio</title>
{% endblock %}
{% block navegacion %}
    {% if user.is_authenticated %}
        
        
    {% else %}
    <form method="post" action="{% url 'apps.blog_auth:sesion' %}">
        {% csrf_token %}
        <button type="submit" class="dropdown-item">Iniciar sesión</button>
    </form>
    <form method="post" action="{% url 'apps.blog_auth:registro' %}">
        {% csrf_token %}
        <button type="submit" class="dropdown-item">Registrarse</button>
    </form>
    {% endif %}
    

    {% if user.is_authenticated %}
    <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username }}
            </button>
            <div class="dropdown-content">
            <form method="post" action="{% url 'apps.blog_auth:cerrar_sesion' %}">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </form>
            </div>
        </div>
    {% endif %}
    {% if perms.post.add_articulo %}
        <div class="dropdown">
            <button>-----Articulo-----</button>
            <div class="dropdown-content">
            <a href="{% url 'apps.post:agregar_articulo' %}">Agregar</a>
            <a href="{% url 'apps.post:listar_articulos' %}">Listar</a>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block contenido %}
<h1></h1>
{% endblock %}

blog/templates/users/registro.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
<title>Registrar usuario</title>
{% endblock %}

{% block navegacion %}
{% endblock %}

{% block contenido %}

<form enctype="multipart/form-data" method="post">{% csrf_token %}
    <section style="margin-top: 5%;" data-bs-version="5.1" class="form4 cid-tf6M1H8RDD mbr-fullscreen" id="form4-12">
        <div class="container">
            <div class="row content-wrapper justify-content-center align-items-center">
                <!-- Formulario -->
                <div class="col-lg-5 col-md-8 mbr-form" data-form-type="formoid">
                    <div class="dragArea row">
                        <div class="col-lg-12">
                            <h1 class="mbr-section-title mb-4 display-4 text-center"><strong>Crear una cuenta</strong></h1>
                        </div>
                        <div class="col-lg-12 mb-4 text-center">
                            <p class="mbr-text mbr-fonts-style display-7">Complete los campos para registrarse</p>
                        </div>

                        <!-- Campos del formulario -->
                        <div class="col-lg-12">
                            <div class="form-group mb-3 form-control form-control-lg">
                                {{ form.username.label_tag }}
                                {{ form.username}}
                                {% if form.username.errors %}
                                    <div class="text-danger">{{ form.username.errors|first }}</div>
                                {% endif %}
                            </div>
                            
                            <div class="form-group mb-3 form-control form-control-lg">
                                {{ form.email.label_tag }}
                                {{ form.email }}
                                {% if form.email.errors %}
                                    <div class="text-danger">{{ form.email.errors|first }}</div>
                                {% endif %}
                            </div>
                            <div class="form-group mb-3 form-control form-control-lg">
                                {{ form.password1.label_tag }}
                                {{ form.password1 }}
                                {% if form.password1.errors %}
                                    <div class="text-danger">{{ form.password1.errors|first }}</div>
                                {% endif %}
                            </div>
                            <div class="form-group mb-3 form-control form-control-lg">
                                {{ form.password2.label_tag }}
                                {{ form.password2 }}
                                {% if form.password2.errors %}
                                    <div class="text-danger">{{ form.password2.errors|first }}</div>
                                {% endif %}
                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-lg w-100">Registrarse</button>
                        </div>
                    </div>
                </div>
                <!-- Imagen al lado del formulario -->
                <div class="col-lg-5 d-none d-lg-block">
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

{% endblock %}

blog/templates/users/sesion.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
<title>Iniciar Sesión</title>
{% endblock %}

{% block navegacion %}
{% endblock %}

{% block contenido %}

<form  method="post">{% csrf_token %}
    <section style="margin-top: 5%;" data-bs-version="5.1" class="form4 cid-tf6M1H8RDD mbr-fullscreen" id="form4-12">
        <div class="container">
            <div class="row content-wrapper justify-content-center align-items-center">
                <!-- Formulario -->
                <div class="col-lg-5 col-md-8 mbr-form" data-form-type="formoid">
                    <div class="dragArea row">
                        <div class="col-lg-12">
                            <h1 class="mbr-section-title mb-4 display-4 text-center"><strong>Iniciar sesión</strong></h1>
                        </div>
                        <div class="col-lg-12 mb-4 text-center">
                            <p class="mbr-text mbr-fonts-style display-7">Complete los campos para iniciar sesion</p>
                        </div>

                        <!-- Campos del formulario -->
                                {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-lg w-100">Iniciar Sesion</button>
                        </div>
                    </div>
                </div>
                <!-- Imagen al lado del formulario -->
                <div class="col-lg-5 d-none d-lg-block">
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

{% endblock %}